((markdown-mode . ((truncate-lines . t)
                   (word-wrap . nil)
                   (line-move-visual . nil)
                   (eval . (visual-line-mode -1))))
 (gfm-mode      . ((truncate-lines . t)
                   (word-wrap . nil)
                   (line-move-visual . nil)
                   (eval . (visual-line-mode -1))))
 (org-mode      . ((truncate-lines . t)
                   (word-wrap . nil)
                   (line-move-visual . nil)
                   (eval . (visual-line-mode -1)))))
